# Generated by Django 6.0.4 on 2026-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_forgot_password_token_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forgot_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
